import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav style={{ padding: '1rem', borderBottom: '1px solid #ddd' }}>
          <a href="/" style={{ marginRight: 12 }}>Start</a>
          <a href="/about" style={{ marginRight: 12 }}>About me</a>
          <a href="/projects">Projects</a>
        </nav>
        {children}
      </body>
    </html>
  );
}
